import os

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")

GOOGLE_CREDENTIALS_FILE = os.getenv(
    "GOOGLE_CREDENTIALS_FILE",
    "credentials/your-service-account.json",
)

STOCK_SPREADSHEET_ID = os.getenv("STOCK_SPREADSHEET_ID", "")
AUXILIARY_SPREADSHEET_ID = os.getenv("AUXILIARY_SPREADSHEET_ID", "")

WORKSHEET_STOCK = os.getenv("WORKSHEET_STOCK", "STOCK")
WORKSHEET_ALMACEN_MOVIMIENTOS = os.getenv(
    "WORKSHEET_ALMACEN_MOVIMIENTOS",
    "Movimientos del almacen",
)
WORKSHEET_DATOS_KARDEX = os.getenv("WORKSHEET_DATOS_KARDEX", "datosKardex")
WORKSHEET_STOCK_ACTUAL = os.getenv("WORKSHEET_STOCK_ACTUAL", "Stock Actual")
